---
version: "2.1"
services:

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: Jackett
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/docker/jackett/downloads:/downloads
    ports:
      - 9004:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: Radarr
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media/Film:/movies
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 9003:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: Sonarr
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 9002:8989
    restart: unless-stopped