---
version: "1.0"
services:

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: Jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/docker/jackett/downloads:/downloads
    ports:
      - 9005:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: Radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/radarr/config:/config
    ports:
      - 9004:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: Sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Download:/downloads
    ports:
      - 9003:8989
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: Transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - USER=BeppeTemp #optional
      - PASS=Cosa@#118StaviF #optional
    volumes:
      - /volume1/docker/transmission/config:/config
      - /volume1/docker/transmission/downloads:/downloads
      - /volume1/docker/transmission/watch:/watch
    ports:
      - 9002:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped