---
version: "3"
services:

  jackett:
    image: lscr.io/linuxserver/jackett
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/docker/jackett/downloads:/downloads
    ports:
      - 50003:9117
    restart: unless-stopped
    deploy:
      mode: global

  radarr:
    image: lscr.io/linuxserver/radarr
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media/Film:/movies
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 50004:7878
    restart: unless-stopped
    deploy:
      mode: global

  sonarr:
    image: lscr.io/linuxserver/sonarr
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 50005:8989
    restart: unless-stopped
    deploy:
      mode: global