---
version: "3"
services:

  flame:
    image: pawelmalak/flame:latest
    volumes:
      - /volume1/docker/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 50002:5005
    environment:
      - PUID=1026
      - PGID=101
      - PASSWORD=Cosa@#118StaviF
    deploy:
      mode: global