version: "3.5"

services:
  pihole:
    image: pihole/pihole:latest
    #hostname: '{{.Node.Hostname}}'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "50001:80/tcp"
    environment:
      PUID: 1034
      PGID: 100
      TZ: 'Europe/Rome'
      WEBPASSWORD: 'dddd'
      # swarm does not support cap_add, this reverts to previous behaviour
      FTL_CMD: 'debug'
      DNSMASQ_LISTENING: 'all'
    volumes:
       - 'pihole_config:/etc/pihole/'
       - 'pihole_dns:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  pihole_config:
  pihole_dns: