version: "3.7"

services:
  pihole:
    image: pihole/pihole:latest
    volumes:
      - /volume1/docker/pihole/config:/etc/pihole
      - /volume1/docker/pihole/dnsmasq:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Rome
      - PIHOLE_DNS_=172.18.0.1#5054 #replace with docker_gwbridge's gateway ip
      - REV_SERVER=true
      - REV_SERVER_CIDR=192.168.0.0/24 #Update these fields to match your environment
      - REV_SERVER_TARGET=192.168.0.254
      - REV_SERVER_DOMAIN=home
      - WEBPASSWORD_FILE=/run/secrets/pihole_webpw
    secrets:
      - pihole_webpw
    networks:
      - traefik
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
      - "80:80/tcp"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.piholeweb.rule=Host(`pihole.home`)
        - traefik.http.routers.piholeweb.entrypoints=web
        - traefik.http.services.piholeweb.loadbalancer.server.port=80
        # 53/udp
        - traefik.udp.routers.pihole-dns-udp.entrypoints=dns-udp
        - traefik.udp.routers.pihole-dns-udp.service=pihole-dns-udp
        - traefik.udp.services.pihole-dns-udp.loadbalancer.server.port=53
        # 53/tcp
        - traefik.tcp.routers.pihole-dns-tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.pihole-dns-tcp.entrypoints=dns-tcp
        - traefik.tcp.routers.pihole-dns-tcp.service=pihole-dns-tcp
        - traefik.tcp.services.pihole-dns-tcp.loadbalancer.server.port=53

networks:
  traefik:
    external: true

secrets:
  pihole_webpw:
    external: true