---
version: "3"
services:

  jackett:
    image: lscr.io/linuxserver/jackett
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/docker/jackett/downloads:/downloads
    ports:
      - 50003:9117
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname!=Home-Nas"

  radarr:
    image: lscr.io/linuxserver/radarr
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media/Film:/movies
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 50004:7878
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname!=Home-Nas"

  sonarr:
    image: lscr.io/linuxserver/sonarr
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 50005:8989
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname!=Home-Nas"

  flame:
    image: pawelmalak/flame:latest
    volumes:
      - /volume1/docker/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 50002:5005
    environment:
      - PUID=1026
      - PGID=101
      - PASSWORD=Cosa@#118StaviF
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==Home-Nas"