version: '3'

services:
  whoami:
    image: traefik/whoami
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public

        - traefik.http.routers.whoami.entrypoints=web
        - traefik.http.routers.whoami.rule=Host(`beppetemp.com`)&&Path(`/whoami`)

        - traefik.http.routers.whoami-https.tls=true
        - traefik.http.routers.whoami-https.entrypoints=websecure
        - traefik.http.routers.whoami-https.tls.certresolver=production
        - traefik.http.routers.whoami-https.rule=Host(`beppetemp.com`)&&Path(`/whoami`)

        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true