version: "3.7"
 
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - config:/config
      - data1:/data1
      - data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==Home-Nas"
volumes:
  config:
    driver: "local"
  data1:
    driver: "local"
  data2:
    driver: "local"
