version: "3.7"
 
services:

  nextcloud:
    image: nextcloud:latest
    depends_on:
      - maindb
    secrets:
      - mysql_root_password
    environment:
      - MYSQL_HOST=maindb:3306
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    ports:
      - 9000:80
    volumes:
      - nextcloud:/var/www/html:cached
      - nextapps:/var/www/html/custom_apps:cached
      - nextdata:/var/www/html/data:cached
      - nextconfig:/var/www/html/config:cached
    networks:
      - traefik-public
    deploy:
      replicas: 1

secrets:
  mysql_root_password:
    external: true 
volumes:
  nextcloud:
    driver: "local"
  nextapps:
    driver: "local"
  nextdata:
    driver: "local"
  nextconfig:
    driver: "local"
networks:
  traefik-public:
    external: true