version: '3'

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
      # Attivazione della dashboard
      - "8080:8080"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      # Definizione configurazioni globali
      - --global.checkNewVersion
      - --global.sendAnonymousUsage

      # Definizione configurazione dashboard
      - --api.dashboard=true
      - --api.insecure=true
      
      # Log di Debug
      # - --log.level=DEBUG

      # Definizione degli entrypoints
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443

      # Definizione del risolutore di certificati

      - --certificatesResolvers.production.acme.email=giuseppe9909@gmail.com
      - --certificatesResolvers.production.acme.storage=/certificates/acme.json
      - --certificatesResolvers.production.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.production.acme.tlschallenge=true
      - --certificatesResolvers.production.acme.httpChallenge.entryPoint=websecure

      # Definizione dei providers
      - --providers.docker=true
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # Attivazione di Traefik
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"

        # Esposizioe su HTTP
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.rule=Host(`traefik.home`)

        # loadbalancer
        - traefik.http.services.traefik.loadbalancer.server.port=8080

        # Definizione del Middleware di redirezione
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

  # whoami:
  #   image: traefik/whoami
  #   networks:
  #     - traefik-public
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     labels:
  #       - traefik.enable=true
  #       - traefik.docker.network=traefik-public
  #       - traefik.http.routers.whoami.entrypoints=web
  #       - traefik.http.routers.whoami.rule=Host(`portainer.home`)
  #       - traefik.http.routers.whoami-https.tls=true
  #       - traefik.http.routers.whoami-https.entrypoints=websecure
  #       - traefik.http.routers.whoami-https.tls.certresolver=production
  #       - traefik.http.routers.whoami-https.rule=Host(`portainer.home`)
  #       - traefik.http.services.whoami.loadbalancer.server.port=80
  
volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true