version: "3"

networks:
  buddy:

volumes:
  prometheus_data:

services:
  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"
    networks:
      - buddy
    platform: linux/amd64

  prometheus:
    image: prom/prometheus:v2.37.7
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./examples/config/on_premise/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=14d"
    ports:
      - "9090:9090"
    networks:
      - buddy
    platform: linux/amd64

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - ./examples/config/on_premise/promtail.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - buddy
    platform: linux/amd64

  buddy:
    image: pubeldev/buddy-prometheus-exporter:latest
    container_name: buddy
    volumes:
      - type: bind
        source: ./examples/config/on_premise/buddy.yaml
        target: /app/buddy.yaml
    ports:
      - "10009:10009"
    networks:
      - buddy
    platform: linux/amd64

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - buddy
    platform: linux/amd64

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./examples/config/on_premise/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - buddy
    platform: linux/amd64


# --- Comando attivazione container x64
# docker run --privileged --rm tonistiigi/binfmt --install amd64 
# https://enlear.academy/run-amd64-docker-images-on-an-arm-computer-208929004510