---
version: "3"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: Home_Assistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /home/beppetemp/config/homeassistant:/config
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: PiHole
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - WEB_PORT=8083
      - TZ=Europe/Rome
    volumes:
       - /home/beppetemp/config/pihole/config:/etc/pihole
       - /home/beppetemp/config/pihole/dns:/etc/dnsmasq.d
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: WatchTower
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # --- Container non usati:

  # homebridge:
  #   image: oznu/homebridge:latest
  #   container_name: Homebridge
  #   network_mode: host
  #   environment:
  #     - PUID=1000
  #     - PGID=100
  #     - TZ=Europe/Rome
  #   volumes:
  #     - /home/beppetemp/config/homebridge:/homebridge
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10mb"
  #       max-file: "1"
  #   restart: always