---
version: "2.1"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: Home_Assistant
    network_mode: host
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /home/pi/homeassistant:/config
    restart: unless-stopped