---
version: "3"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: Home_Assistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /home/beppetemp/config/homeassistant:/config
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: PiHole
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - WEB_PORT=8083
      - TZ=Europe/Rome
    volumes:
       - /home/beppetemp/config/pihole/config:/etc/pihole/
       - /home/beppetemp/config/pihole/dns:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  #homebridge:
  #  image: oznu/homebridge:latest
  #  container_name: Homebridge
  #  network_mode: host
  #  environment:
  #    - PUID=1000
  #    - PGID=100
  #    - TZ=Europe/Rome
  #  volumes:
  #    - /home/beppetemp/config/homebridge:/homebridge
  #  logging:
  #    driver: json-file
  #    options:
  #      max-size: "10mb"
  #      max-file: "1"
  #  restart: always