---
version: "2.1"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: Plex
    network_mode: host
    environment:
      - PUID=1034
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM=claim-Rdsy1Hs7-6GcDiJZoUUH
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Film:/movies
    restart: unless-stopped
    devices:
      - "/dev/dri:/dev/dri"