---
version: "2.1"

services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: Prowlarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped