---
version: "3"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    networks:
      - traefik-public
    volumes:
      - /volume1/docker/prowlarr:/config
    ports:
      - 9696:9696
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==Raspi-NodeOne"

  radarr:
    image: lscr.io/linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    networks:
      - traefik-public  
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media/Film:/movies
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 7878:7878
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==Raspi-NodeOne"

  sonarr:
    image: lscr.io/linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    networks:
      - traefik-public 
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 8989:8989
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==Raspi-NodeOne"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=9090
    networks:
      - traefik-public 
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/media/Downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9090:9090
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==Raspi-Master"

networks:
  traefik-public:
    external: true