---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: Qbittorrent
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
      - WEBUI_PORT=9090
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/media/Downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9090:9090
    restart: unless-stopped
