---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media/Film:/movies
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 7878:7878
    restart: unless-stopped