---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 8989:8989
    restart: unless-stopped