---
version: "2.1"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: Plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=101
      - VERSION=docker
      - PLEX_CLAIM=claim-Rdsy1Hs7-6GcDiJZoUUH
    volumes:
      - /volume1/docker/container-config/plex:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Film:/movies
      - /volume1/photo:/photo
    restart: unless-stopped
    devices:
      - "/dev/dri:/dev/dri"

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: Prowlarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/container-config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: Radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/container-config/radarr/config:/config
      - /volume1/media/Film:/movies
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: Sonarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/container-config/sonarr/config:/config
      - /volume1/media/Serie-TV:/tv
      - /volume1/media/Downloads:/volume1/media/Downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: Qbittorrent
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
      - WEBUI_PORT=9090
    volumes:
      - /volume1/docker/container-config/qbittorrent:/config
      - /volume1/media/Downloads:/downloads
    ports:
      - 9090:9090
    restart: unless-stopped

  vscode:
    image: lscr.io/linuxserver/code-server
    container_name: Vscode
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/container-config/vscode:/config
      - /volume1/docker/composers:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped

  flame:
    image: pawelmalak/flame
    container_name: Flame
    ports:
      - 5005:5005
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
      - PASSWORD=metin2server
    volumes:
      - /volume1/docker/container-config/flame:/app/data
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-server
    container_name: Minecraft
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    volumes:
      - /volume1/docker/container-config/minecraft:/data
    ports:
      - 25565:25565
    restart: unless-stopped

  Freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/container-config/freshrss:/config
    ports:
      - 10110:80
    restart: unless-stopped

volumes:
  dbdata:
  traefik-public-certificates: