version: '2.2'

services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 9050:80
    volumes:
      - /volume1/docker/podsync/data:/app/data/
      - /volume1/docker/podsync:/app/config.toml
    restart: always